export const FETCH_TODOS = 'FETCH_TODOS';
export const FETCHING_TODOS = 'FETCHING_TODOS';

export const CREATE_TODO = 'CREATE_TODO';
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';
export const CREATE_TODO_FAILURE = 'CREATE_TODO_FAILURE';
